/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#004a66",
        "tertiary-fixed": "#c4e7ff",
        "surface-tint": "#2151da",
        "on-secondary-fixed": "#0d1c32",
        "primary-fixed": "#dce1ff",
        "error-container": "#ffdad6",
        "surface-container": "#e6eeff",
        "on-primary-fixed-variant": "#0039b5",
        "on-tertiary-container": "#a3dcff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d2e0fe",
        "surface-dim": "#ccdbf4",
        "on-primary-container": "#cad3ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001551",
        "on-tertiary-fixed-variant": "#004c69",
        "on-tertiary-fixed": "#001e2c",
        "on-surface-variant": "#434655",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#ebf1ff",
        "secondary": "#515f78",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d6e3ff",
        "outline": "#747686",
        "surface-container-highest": "#d5e3fd",
        "outline-variant": "#c4c5d7",
        "primary-container": "#1d4ed8",
        "on-secondary-container": "#55637d",
        "secondary-fixed-dim": "#b9c7e4",
        "surface-container-low": "#eff4ff",
        "on-error": "#ffffff",
        "inverse-surface": "#233144",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#39475f",
        "on-background": "#0d1c2f",
        "surface-container-high": "#dde9ff",
        "surface-variant": "#d5e3fd",
        "tertiary-container": "#006387",
        "on-surface": "#0d1c2f",
        "inverse-primary": "#b7c4ff",
        "primary": "#0037b0",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b7c4ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin-desktop": "2rem",
        "space-xl": "2rem",
        "space-sm": "0.5rem",
        "gutter": "1rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.25rem"
      },
      fontFamily: {
        "display-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "metric-display": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-sm": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "display-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "metric-display": ["1.875rem", { lineHeight: "2.25rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
